



#include "board.h"



#define		CLOCKPIN_CHAR		A
#define		CLOCKPIN_NUM		1


#define		CLOCKPIN_DDR		DEF_DDR(CLOCKPIN_CHAR)
#define		CLOCKPIN_PORT		DEF_PORT(CLOCKPIN_CHAR)
#define		CLOCKPIN_MASK		_BV(CLOCKPIN_NUM)
#define		CLOCKPIN			DEF_PTX(CLOCKPIN_CHAR, CLOCKPIN_NUM)


#define		LEDPIN_CHAR		A
#define		LEDPIN_NUM		2


#define		LEDPIN_DDR		DEF_DDR(LEDPIN_CHAR)
#define		LEDPIN_PORT		DEF_PORT(LEDPIN_CHAR)
#define		LEDPIN_MASK		_BV(LEDPIN_NUM)
#define		LEDPIN			DEF_PTX(LEDPIN_CHAR, LEDPIN_NUM)



#define		SENDLED_CHAR	A
#define		SENDLED_NUM		3

#define		SENDLED_DDR		DEF_DDR(SENDLED_CHAR)
#define		SENDLED_PORT	DEF_PORT(SENDLED_CHAR)
#define		SENDLED_MASK	_BV(SENDLED_NUM)
#define		SENDLED			DEF_PTX(SENDLED_CHAR, SENDLED_NUM)






// #define		TIMER_N			B
// #define		TIMER_IRQ		15
